# generated by datamodel-codegen:
#   filename:  action-plan.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class RiskHint(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class StopIfEnum(Enum):
    navigation_to_other_origin = 'navigation_to_other_origin'
    captcha_detected = 'captcha_detected'
    form_error_shown = 'form_error_shown'


class TextRunId(RootModel[constr(pattern=r'^t-[0-9a-z]+$')]):
    root: constr(pattern=r'^t-[0-9a-z]+$')


class FrameId(RootModel[constr(pattern=r'^f-[0-9]+$')]):
    root: constr(pattern=r'^f-[0-9]+$')


class SessionId(
    RootModel[
        constr(
            pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        )
    ]
):
    root: constr(
        pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ) = Field(
        ...,
        description='UUIDv4-shaped. A pattern, not format:uuid, so the standalone Ajv validator needs no runtime format module.',
    )


class Box(RootModel[list[float]]):
    """
    [x, y, w, h] in CSS pixels, top-level viewport, origin top-left
    """

    root: list[float] = Field(
        ...,
        description='[x, y, w, h] in CSS pixels, top-level viewport, origin top-left',
        max_length=4,
        min_length=4,
    )


class EntityType(Enum):
    PASSWORD = 'PASSWORD'
    OTP = 'OTP'
    CARD_NUMBER = 'CARD_NUMBER'
    CARD_CVV = 'CARD_CVV'
    CARD_EXPIRY = 'CARD_EXPIRY'
    AADHAAR = 'AADHAAR'
    FACE = 'FACE'
    ID_DOCUMENT = 'ID_DOCUMENT'
    SIGNATURE = 'SIGNATURE'
    QR_CODE = 'QR_CODE'
    SECRET = 'SECRET'
    EMAIL = 'EMAIL'
    PHONE = 'PHONE'
    ADDRESS = 'ADDRESS'
    DOB = 'DOB'
    BANK_ACCOUNT = 'BANK_ACCOUNT'
    PAN = 'PAN'
    GSTIN = 'GSTIN'
    IFSC = 'IFSC'
    UPI_VPA = 'UPI_VPA'
    PASSPORT = 'PASSPORT'
    VEHICLE_REG = 'VEHICLE_REG'
    PERSON_NAME = 'PERSON_NAME'
    USERNAME = 'USERNAME'
    PIN_CODE = 'PIN_CODE'
    DATE = 'DATE'
    AMOUNT = 'AMOUNT'
    CITY = 'CITY'
    COUNTRY = 'COUNTRY'
    UNKNOWN_SENSITIVE = 'UNKNOWN_SENSITIVE'
    CAPTCHA = 'CAPTCHA'
    MEDIA = 'MEDIA'
    LIVE = 'LIVE'


class Sensitivity(Enum):
    CRITICAL = 'CRITICAL'
    HIGH = 'HIGH'
    MEDIUM = 'MEDIUM'
    LOW = 'LOW'


class Channel(Enum):
    dom = 'dom'
    text_dom = 'text-dom'
    text_ocr = 'text-ocr'
    ner = 'ner'
    vision = 'vision'


class Expect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: constr(max_length=40) | None = None
    name: constr(max_length=120) | None = None
    box_tolerance_px: conint(ge=0, le=64) | None = None


class Action1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['click']
    node: constr(pattern=r'^n-[0-9a-z]+$')
    expect: Expect | None = None


class Action2(BaseModel):
    """
    type with a vault ref (OQ-1). Disjoint from the literal-text branch below — 'text' is deliberately not a declared property here, so a payload carrying both is rejected by additionalProperties:false rather than relying on an inner oneOf, which a JSON-Schema-to-Pydantic generator can silently flatten into two independently-optional fields (see Phase 1 Implementation Notes).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['type']
    node: constr(pattern=r'^n-[0-9a-z]+$')
    ref: constr(pattern=r'^⟪[A-Z_]+#[0-9]+⟫$')
    clear_first: bool | None = None
    expect: Expect | None = None


class Action3(BaseModel):
    """
    type with literal text (OQ-14). If OQ-14 is decided 'no', delete this branch entirely — a one-hunk change, as design.md §4.6 intends.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['type']
    node: constr(pattern=r'^n-[0-9a-z]+$')
    text: constr(max_length=500)
    clear_first: bool | None = None
    expect: Expect | None = None


class Action4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['select']
    node: constr(pattern=r'^n-[0-9a-z]+$')
    option: constr(max_length=200)
    expect: Expect | None = None


class Direction(Enum):
    up = 'up'
    down = 'down'
    left = 'left'
    right = 'right'


class Amount(Enum):
    small = 'small'
    page = 'page'
    end = 'end'


class Action5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['scroll']
    direction: Direction
    amount: Amount | None = None
    node: constr(pattern=r'^n-[0-9a-z]+$') | None = None


class Action6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['wait']
    ms: conint(ge=50, le=5000)


class Action7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['click_point']
    x: float
    y: float
    label: constr(max_length=80)


class Level(Enum):
    L1 = 'L1'
    L2 = 'L2'


class Action8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['request_observation']
    level: Level
    region: Box | None = None


class Action9(BaseModel):
    """
    content may carry placeholders; the panel resolves them locally for display only, never re-sends them resolved.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['report']
    title: constr(max_length=80) | None = None
    content: constr(max_length=4000)


class Action10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['ask_user']
    question: constr(max_length=300)


class Action11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['done']
    summary: constr(max_length=300) | None = None


class Reason(Enum):
    captcha = 'captcha'
    blocked = 'blocked'
    cannot_proceed = 'cannot_proceed'
    unsafe = 'unsafe'


class Action12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: Literal['stop']
    reason: Reason


class ActionPlan(BaseModel):
    """
    design.md §4.5/§4.6. Also used as the vLLM structured-decoding grammar (Phase 2, T-2.36) — a hallucinated action is a parse error, not a click.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    step_id: constr(pattern=r'^s-[0-9]+$')
    plan_id: constr(max_length=40) | None = None
    actions: list[
        Action1
        | Action2
        | Action3
        | Action4
        | Action5
        | Action6
        | Action7
        | Action8
        | Action9
        | Action10
        | Action11
        | Action12
    ] = Field(..., max_length=5, min_length=1)
    risk_hint: RiskHint | None = None
    stop_if: list[StopIfEnum] | None = None
    note: constr(max_length=200) | None = None
