# generated by datamodel-codegen:
#   filename:  common.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import Field, RootModel, constr


class AegisCommonDefinitions(RootModel[Any]):
    root: Any = Field(..., title='AEGIS common definitions')


class NodeId(RootModel[constr(pattern=r'^n-[0-9a-z]+$')]):
    root: constr(pattern=r'^n-[0-9a-z]+$')


class TextRunId(RootModel[constr(pattern=r'^t-[0-9a-z]+$')]):
    root: constr(pattern=r'^t-[0-9a-z]+$')


class FrameId(RootModel[constr(pattern=r'^f-[0-9]+$')]):
    root: constr(pattern=r'^f-[0-9]+$')


class StepId(RootModel[constr(pattern=r'^s-[0-9]+$')]):
    root: constr(pattern=r'^s-[0-9]+$')


class SessionId(
    RootModel[
        constr(
            pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        )
    ]
):
    root: constr(
        pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ) = Field(
        ...,
        description='UUIDv4-shaped. A pattern, not format:uuid, so the standalone Ajv validator needs no runtime format module.',
    )


class PlaceholderRef(RootModel[constr(pattern=r'^⟪[A-Z_]+#[0-9]+⟫$')]):
    root: constr(pattern=r'^⟪[A-Z_]+#[0-9]+⟫$')


class Box(RootModel[list[float]]):
    """
    [x, y, w, h] in CSS pixels, top-level viewport, origin top-left
    """

    root: list[float] = Field(
        ...,
        description='[x, y, w, h] in CSS pixels, top-level viewport, origin top-left',
        max_length=4,
        min_length=4,
    )


class EntityType(Enum):
    PASSWORD = 'PASSWORD'
    OTP = 'OTP'
    CARD_NUMBER = 'CARD_NUMBER'
    CARD_CVV = 'CARD_CVV'
    CARD_EXPIRY = 'CARD_EXPIRY'
    AADHAAR = 'AADHAAR'
    FACE = 'FACE'
    ID_DOCUMENT = 'ID_DOCUMENT'
    SIGNATURE = 'SIGNATURE'
    QR_CODE = 'QR_CODE'
    SECRET = 'SECRET'
    EMAIL = 'EMAIL'
    PHONE = 'PHONE'
    ADDRESS = 'ADDRESS'
    DOB = 'DOB'
    BANK_ACCOUNT = 'BANK_ACCOUNT'
    PAN = 'PAN'
    GSTIN = 'GSTIN'
    IFSC = 'IFSC'
    UPI_VPA = 'UPI_VPA'
    PASSPORT = 'PASSPORT'
    VEHICLE_REG = 'VEHICLE_REG'
    PERSON_NAME = 'PERSON_NAME'
    USERNAME = 'USERNAME'
    PIN_CODE = 'PIN_CODE'
    DATE = 'DATE'
    AMOUNT = 'AMOUNT'
    CITY = 'CITY'
    COUNTRY = 'COUNTRY'
    UNKNOWN_SENSITIVE = 'UNKNOWN_SENSITIVE'
    CAPTCHA = 'CAPTCHA'
    MEDIA = 'MEDIA'
    LIVE = 'LIVE'


class Sensitivity(Enum):
    CRITICAL = 'CRITICAL'
    HIGH = 'HIGH'
    MEDIUM = 'MEDIUM'
    LOW = 'LOW'


class Channel(Enum):
    dom = 'dom'
    text_dom = 'text-dom'
    text_ocr = 'text-ocr'
    ner = 'ner'
    vision = 'vision'
