# generated by datamodel-codegen:
#   filename:  error.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, constr


class Code(Enum):
    SCHEMA_INVALID = 'SCHEMA_INVALID'
    UNAUTHORIZED = 'UNAUTHORIZED'
    SESSION_NOT_FOUND = 'SESSION_NOT_FOUND'
    STEP_OUT_OF_ORDER = 'STEP_OUT_OF_ORDER'
    PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE'
    PLAN_INVALID = 'PLAN_INVALID'
    RATE_LIMITED = 'RATE_LIMITED'
    MODEL_UNAVAILABLE = 'MODEL_UNAVAILABLE'
    MODEL_TIMEOUT = 'MODEL_TIMEOUT'


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Code
    message: constr(max_length=500)
    request_id: constr(max_length=64)
    retryable: bool


class ErrorResponse(BaseModel):
    """
    design.md §4.7.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    error: Error
