# generated by datamodel-codegen:
#   filename:  sanitized-context.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr


class Reason(Enum):
    initial = 'initial'
    after_action = 'after_action'
    requested = 'requested'
    reconcile = 'reconcile'


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    w: confloat(ge=0.0)
    h: confloat(ge=0.0)
    dpr: confloat(ge=0.0)
    scroll_y: float
    doc_h: confloat(ge=0.0)


class Category(Enum):
    gov = 'gov'
    banking = 'banking'
    email = 'email'
    social = 'social'
    health = 'health'
    docs = 'docs'
    canvas_app = 'canvas_app'
    unknown = 'unknown'


class Page(BaseModel):
    """
    OQ-11 default: category only, never an origin or URL.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    category: Category
    title: constr(max_length=200) = Field(..., description='Sanitized page title.')


class Reason1(Enum):
    canvas = 'canvas'
    img = 'img'
    video = 'video'
    iframe_blocked = 'iframe-blocked'
    svg_text = 'svg-text'
    embed = 'embed'
    other = 'other'


class Status(Enum):
    grey = 'grey'
    analysed = 'analysed'


class Coverage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cleared: confloat(ge=0.0, le=1.0)
    redacted: confloat(ge=0.0, le=1.0)
    unanalysed: confloat(ge=0.0, le=1.0)


class Action(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    op: str


class SessionId(
    RootModel[
        constr(
            pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        )
    ]
):
    root: constr(
        pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ) = Field(
        ...,
        description='UUIDv4-shaped. A pattern, not format:uuid, so the standalone Ajv validator needs no runtime format module.',
    )


class Box(RootModel[list[float]]):
    """
    [x, y, w, h] in CSS pixels, top-level viewport, origin top-left
    """

    root: list[float] = Field(
        ...,
        description='[x, y, w, h] in CSS pixels, top-level viewport, origin top-left',
        max_length=4,
        min_length=4,
    )


class EntityType(Enum):
    PASSWORD = 'PASSWORD'
    OTP = 'OTP'
    CARD_NUMBER = 'CARD_NUMBER'
    CARD_CVV = 'CARD_CVV'
    CARD_EXPIRY = 'CARD_EXPIRY'
    AADHAAR = 'AADHAAR'
    FACE = 'FACE'
    ID_DOCUMENT = 'ID_DOCUMENT'
    SIGNATURE = 'SIGNATURE'
    QR_CODE = 'QR_CODE'
    SECRET = 'SECRET'
    EMAIL = 'EMAIL'
    PHONE = 'PHONE'
    ADDRESS = 'ADDRESS'
    DOB = 'DOB'
    BANK_ACCOUNT = 'BANK_ACCOUNT'
    PAN = 'PAN'
    GSTIN = 'GSTIN'
    IFSC = 'IFSC'
    UPI_VPA = 'UPI_VPA'
    PASSPORT = 'PASSPORT'
    VEHICLE_REG = 'VEHICLE_REG'
    PERSON_NAME = 'PERSON_NAME'
    USERNAME = 'USERNAME'
    PIN_CODE = 'PIN_CODE'
    DATE = 'DATE'
    AMOUNT = 'AMOUNT'
    CITY = 'CITY'
    COUNTRY = 'COUNTRY'
    UNKNOWN_SENSITIVE = 'UNKNOWN_SENSITIVE'
    CAPTCHA = 'CAPTCHA'
    MEDIA = 'MEDIA'
    LIVE = 'LIVE'


class Sensitivity(Enum):
    CRITICAL = 'CRITICAL'
    HIGH = 'HIGH'
    MEDIUM = 'MEDIUM'
    LOW = 'LOW'


class Channel(Enum):
    dom = 'dom'
    text_dom = 'text-dom'
    text_ocr = 'text-ocr'
    ner = 'ner'
    vision = 'vision'


class NodeValue1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['empty']


class NodeValue2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['presence']
    entity: EntityType
    len: conint(ge=0)


class NodeValue3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['placeholder']
    ref: constr(pattern=r'^⟪[A-Z_]+#[0-9]+⟫$')
    entity: EntityType
    len: conint(ge=0)


class NodeValue4(BaseModel):
    """
    Only for LOW-class or non-sensitive values that passed analysis.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['text']
    text: constr(max_length=500)


class State(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    focused: bool | None = None
    disabled: bool | None = None
    readonly: bool | None = None
    required: bool | None = None
    checked: bool | None = None
    expanded: bool | None = None
    selected: bool | None = None
    has_value: bool | None = None
    value_len: conint(ge=0) | None = None
    occluded: bool | None = None
    volatile: bool | None = None


class Affordance(Enum):
    click = 'click'
    type = 'type'
    select = 'select'
    toggle = 'toggle'
    scroll = 'scroll'


class SanitizedNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^n-[0-9a-z]+$')
    role: constr(max_length=40)
    name: constr(max_length=200)
    box: Box
    frame: constr(pattern=r'^f-[0-9]+$')
    z: int
    state: State
    affordances: list[Affordance]
    value: NodeValue1 | NodeValue2 | NodeValue3 | NodeValue4 | None = None


class SanitizedTextRun(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^t-[0-9a-z]+$')
    box: Box
    text: constr(max_length=4000) = Field(
        ..., description='Sanitized — placeholders already substituted.'
    )


class Method(Enum):
    placeholder = 'placeholder'
    fill = 'fill'


class RedactionLegendEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref: constr(pattern=r'^⟪[A-Z_]+#[0-9]+⟫$') | None = None
    entity: EntityType
    class_: Sensitivity = Field(..., alias='class')
    len: conint(ge=0) | None = None
    boxes: list[Box]
    method: Method
    confidence: confloat(ge=0.0, le=1.0)
    sources: list[constr(max_length=60)]
    unverified: bool


class Level(Enum):
    L1 = 'L1'
    L2 = 'L2'


class ImagePart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    level: Level
    region: Box
    scale: confloat(ge=0.0)
    format: Literal['image/webp']
    sha256: constr(pattern=r'^[0-9a-f]{64}$')
    data: str = Field(..., json_schema_extra={'contentEncoding': 'base64'})
    legend: constr(max_length=300)


class UnexplainedItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    box: Box
    reason: Reason1
    status: Status


class HistoryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step_id: constr(pattern=r'^s-[0-9]+$')
    actions: list[Action]
    outcome: constr(max_length=200)


class SanitizedcontextSteprequest(BaseModel):
    """
    design.md §4.3. Everything the client sends to the gateway for one step. No field in this schema may hold a URL, a CSS selector, an XPath, or a page origin — that is enforced structurally, not by convention.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: Literal['AEGIS/1'] = Field(..., alias='schema')
    step_id: constr(pattern=r'^s-[0-9]+$')
    task: constr(max_length=2000) = Field(
        ...,
        description='Sanitized task text (Channel T + placeholder substitution already applied).',
    )
    reason: Reason
    delta_of: constr(pattern=r'^s-[0-9]+$') | None = None
    viewport: Viewport
    page: Page = Field(
        ..., description='OQ-11 default: category only, never an origin or URL.'
    )
    nodes: list[SanitizedNode]
    removed: list[constr(pattern=r'^n-[0-9a-z]+$')] | None = Field(
        None, description='Delta only: node ids no longer present.'
    )
    text: list[SanitizedTextRun]
    redactions: list[RedactionLegendEntry]
    unexplained: list[UnexplainedItem]
    coverage: Coverage
    image: ImagePart | None = None
    history: list[HistoryItem] = Field(..., max_length=5)
    client_timing: dict[str, confloat(ge=0.0)]
